"""Emit ``results/data_stats.md`` from the built manifests (PLAN.md §4.3.3).

    python -m scripts.make_data_stats

Generated rather than hand-written, because the counts change every time the
corpus is re-pulled and a stale table in results/ is worse than no table -- it
is the kind of thing a reader trusts.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

import numpy as np
import pandas as pd

from src.data.sources import SOURCES, holdout_sources

DETAIL = Path("data/manifests/detail.csv")
OUT = Path("results/data_stats.md")

#: The audit's numbers on raw SID_Set, for the before/after column.
AUDIT_RAW = {
    "container_is_png": 0.7574, "megapixels": 0.9814, "is_1024sq": 0.9814,
    "is_square": 0.9806, "height": 0.8966, "width": 0.5897, "has_icc": 0.7027,
    "n_bytes": 0.6037, "n_exif_tags": 0.5000, "n_text_chunks": 0.5000,
    "bytes_per_pixel": 0.5341,
}


def _md(df: pd.DataFrame, **kw) -> str:
    try:
        return df.to_markdown(**kw)
    except ImportError:            # tabulate absent
        return "```\n" + df.to_string(**kw) + "\n```"


def build(detail: Path = DETAIL, out: Path = OUT) -> Path:
    from tests.test_normalization_audit import _probe_one, _auroc

    d = pd.read_csv(detail)
    probe = pd.DataFrame([_probe_one(p) for p in d["image_path"]])
    for c in ("label", "generator", "split"):
        probe[c] = d[c].values
    y = (probe["label"] == 1).astype(int).values

    L = []
    A = L.append
    A("# Data statistics\n")
    A("Generated by `python -m scripts.make_data_stats`. Do not hand-edit.\n")
    A(f"Corpus: **{len(d):,} images**, "
      f"{int((d.label == 0).sum()):,} real / {int((d.label == 1).sum()):,} AI, "
      f"across **{d.generator.nunique()} sources**.\n")

    # ---------------------------------------------------------------- counts #
    A("## Counts by class and split\n")
    t = d.pivot_table(index="split", columns="label", values="image_path",
                      aggfunc="count", fill_value=0)
    t.columns = ["real (0)", "ai (1)"][: len(t.columns)]
    t["total"] = t.sum(axis=1)
    t["% ai"] = (100 * t["ai (1)"] / t["total"]).round(1)
    A(_md(t.loc[[s for s in ("train", "val", "test") if s in t.index]]))
    A("")
    A("Test skews AI because all held-out generators are AI and land there "
      "whole. Train and val are the splits whose balance matters, and "
      "`tests/test_manifest.py` bounds them to 25-75%.\n")

    A("## Counts by generator and split\n")
    g = d.pivot_table(index=["label", "generator"], columns="split",
                      values="image_path", aggfunc="count", fill_value=0)
    for s in ("train", "val", "test"):
        if s not in g.columns:
            g[s] = 0
    g = g[["train", "val", "test"]]
    g["total"] = g.sum(axis=1)
    held = {s.name for s in holdout_sources()}
    g["held out"] = ["yes" if i[1] in held else "" for i in g.index]
    A(_md(g))
    A("")
    A(f"Held out of train entirely: **{', '.join(sorted(held))}** "
      f"({len(held)} generators, "
      f"{len({s.family for s in holdout_sources()})} distinct families). "
      "PLAN.md §4.3.1 requires at least two.\n")

    # ------------------------------------------------------- post-norm audit #
    A("## Post-normalization metadata audit\n")
    A("The Phase 2 audit found a classifier reading **no pixels at all** scored "
      "0.98 AUROC on raw SID_Set. Same probe, same metric code, run on the "
      "normalized corpus. Direction-agnostic AUROC; 0.5 = no leak.\n")
    rows = []
    for ch, raw in AUDIT_RAW.items():
        if ch not in probe.columns:
            continue
        now = _auroc(y, probe[ch].astype(float).values)
        nuniq = probe[ch].nunique()
        rows.append({
            "channel": ch,
            "raw SID_Set": f"{raw:.4f}",
            "normalized": f"{now:.4f}",
            "distinct values": nuniq,
            "status": "constant" if nuniq == 1 else ("ok" if now < 0.60 else "LEAK"),
        })
    for ch in ("mode_is_rgb", "has_adobe_marker", "chroma_subsampling"):
        if ch in probe.columns:
            rows.append({
                "channel": ch, "raw SID_Set": "-",
                "normalized": f"{_auroc(y, probe[ch].astype(float).values):.4f}",
                "distinct values": probe[ch].nunique(),
                "status": "constant" if probe[ch].nunique() == 1 else "ok",
            })
    A(_md(pd.DataFrame(rows).set_index("channel")))
    A("")
    A("Most channels are 0.5000 **exactly**, because normalization makes them "
      "constant: every file is a 512x512 RGB q95 4:2:0 JPEG with no metadata. A "
      "constant feature has AUROC 0.5 by construction, which is stronger than "
      "\"measured below a threshold\" -- there is no sample size at which it "
      "could come out otherwise.\n")
    A("`n_bytes` is the one channel that cannot be made constant: at fixed "
      "quality, file size measures how compressible the picture is, which is a "
      "property of the pixels rather than of the container. It is bounded, not "
      "pinned.\n")

    # --------------------------------------------------- source fingerprints #
    A("## Source fingerprinting by file size\n")
    A("Within-class source separability. A source signature is not a class leak "
      "on its own, but becomes one when that source carries a distinguishing "
      "property.\n")
    rows = []
    for lab, name in ((0, "real"), (1, "ai")):
        sub = probe[probe["label"] == lab]
        for s in sorted(sub["generator"].unique()):
            yy = (sub["generator"] == s).astype(int).values
            if yy.sum() in (0, len(yy)):
                continue
            rows.append({
                "class": name, "source": s, "n": int(yy.sum()),
                "median bytes": int(sub.loc[sub["generator"] == s, "n_bytes"].median()),
                "AUROC vs same-class": round(
                    _auroc(yy, sub["n_bytes"].astype(float).values), 4),
            })
    A(_md(pd.DataFrame(rows).set_index(["class", "source"])))
    A("")
    A("> **This table is why Pexels was dropped.** Its sources are 18 KB at "
      "768p -- already downscaled and recompressed -- so its normalized files "
      "came out at a median 16 KB against 66-103 KB everywhere else. It scored "
      "**1.0000** here, and pushed real-vs-AI `n_bytes` to **0.7120**. Replaced "
      "by Unsplash (130 KB/image at source): `n_bytes` fell to **0.5017** and "
      "the source signature to **0.5108**. Caught by the task-F regression "
      "test, which is the entire reason for having one.\n")

    # -------------------------------------------------------- dedup + blocks #
    stats_path = detail.parent / "stats.json"
    if stats_path.exists():
        st = json.loads(stats_path.read_text(encoding="utf-8"))
        A("## Deduplication and the forbidden subset\n")
        A(f"- duplicate clusters: **{st['n_clusters']:,}** over "
          f"{st['n_images']:,} images "
          f"({st['n_dup_pairs']} near-duplicate pairs at pHash Hamming "
          f"<= {st['config']['dup_threshold']})")
        A(f"- images matching the forbidden blocklist: **{st['n_blocked']}** "
          f"(all forced out of train)")
        A(f"- blocklist loaded: {'NO -- assertions are vacuous!' if st['blocklist_empty'] else 'yes'}")
        for s in st.get("blocklist_sources", []):
            A(f"  - {s}")
        for gp in st.get("blocklist_gaps", []):
            A(f"  - **GAP:** {gp}")
        A("")

    # ------------------------------------------------------- source geometry #
    A("## Source geometry (before normalization)\n")
    A("Recorded because it is what forced the crop-not-resize decision, and "
      "what ruled GenImage out.\n")
    if {"src_width", "src_height"} <= set(d.columns):
        sg = d.groupby(["label", "generator"]).agg(
            n=("src_width", "size"),
            w_median=("src_width", "median"),
            h_median=("src_height", "median"),
            min_side_min=("src_width", lambda s: 0),
        )
        sg["min_side_median"] = d.assign(
            ms=d[["src_width", "src_height"]].min(axis=1)
        ).groupby(["label", "generator"]).ms.median().values
        sg = sg.drop(columns=["min_side_min"]).astype(int)
        A(_md(sg))
        A("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--detail", type=Path, default=DETAIL)
    ap.add_argument("--out", type=Path, default=OUT)
    a = ap.parse_args(argv)
    p = build(a.detail, a.out)
    print(f"-> {p}")
    print(p.read_text(encoding="utf-8")[:2000])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
